### ISSUE TITLE
Should actually use the distance matrix instead of looping

### ISSUE THREAD

**Issue by MichaelChirico** [rodazuero/gmapsdistance#12]
https://developers.google.com/maps/documentation/distance-matrix/intro

We can use `paste(origins, collapse = "|")` and then properly parse the output table to get the full distance matrix in one API call.

E.g.

```
or = c("Washington+DC", "New+York+City")
de = c("Philadelphia", "Pittsburgh")
url = 
  paste0("https://maps.googleapis.com/maps/api/distancematrix/xml?",
         "origins=", paste(or, collapse = "|"),
         "&destinations=", paste(de, collapse = "|"),
         "&mode=", "driving",
         "&sensor=", "false",
         "&units=metric",
         "&departure_time=", "now",
         "&traffic_model=", "best_guess")
```

Basic idea is very simple; tough will be dealing with errors in this more complicated environment...

**Comment by Demetrio92** [comment]
Seems to be used already, but not sure if in the optimal way. Especially, I still see a loop there...

**Comment by zoller27osu** [comment]
The substance of this issue (using paste(origins, collapse = "|") and paste(destinations, collapse = "|") to batch distance requests in the same query, resulting in much faster gmapsdistance execution) has not been addressed.
It isn't actually quite that simple, since there are [limits](https://developers.google.com/maps/documentation/distance-matrix/usage-and-billing): "Maximum of 25 origins or 25 destinations per request" and "Maximum 100 elements per client-side request.", where "elements", I believe, is the product of origins and destinations.
So it would essentially need a singly nested for loop finding the distance between 4, 10, or 25 origins and 25, 10, or 4 destinations in each request.
I personally think the speedup would still be worth the coding pain, assuming Google doesn't mess with the output format much more.

**Comment by Demetrio92** [comment]
@zoller27osu I created a new issue summarizing the discussion here. 
Thanks for letting us know, the issue got lost along multiple actual bug reports (this one is an enhancement really). 

Imho, it's super easy to fix, by looping over a sequence with a step, like: 
```R
for i in seq(1, n, step) {
   origins_to_pass = paste(na.exclude(x[1:4]), collapse='|')
   destinations_to_pass = paste(na.exclude(destinations[i, i+step]), collapse = "|")
   ...
} 
```

Feel free to fork the repo, implement this simple fix, test it and submit a PR. Ideally with some microbenchmark testing. I will gladly merge it. 
Otherwise I will get my hands on the issue some time in the future. It's not critical for now.
