### ISSUE TITLE
Errors with mode = transit

### ISSUE THREAD

**Issue by Alserina** [rodazuero/gmapsdistance#19]
I am able to run code if I set mode = bicycling, walking, or driving. However, when I set mode = transit, even when the start and end locations are transit stops on the same train line within the same city, I get the following error:

> results2 = gmapsdistance(origin = "42.362660+-71.058134", 
>                         destination = "42.352572+-71.064820", 
>                         mode = "transit",
>                         dep_date = "2017-08-16", 
>                         dep_time = "20:40:00")

>Error in UseMethod("xmlChildren") : 
 > no applicable method for 'xmlChildren' applied to an object of class "NULL"

Can someone please advise on what I am doing wrong? Thanks!

**Comment by rodazuero** [comment]
Are you using a google maps API key? note that you can only use this option if you set an API key. 
From the help file:

dep_date	
Instead of using the departure option, the user can set the departure date and time using dep_date and dep_time options.
If no value is set for departure, dep_date and dep_time, the departure time is set to the present.
**ONLY works with a Google Maps API key AND MUST be according to UCT time.**

**Comment by Alserina** [comment]
Yes, I have an API key that I defined using set.api.key().

**Comment by Demetrio92** [comment]
Fixed. Although the API returns "route not found", so that was probably causing the error before. 
Please don't forget to provide the API key for transit mode. 

FIX: `devtools::install_github("rodazuero/gmapsdistance")`
CRAN update coming soon
