### ISSUE TITLE
Report bug Input is not proper UTF-8, indicate encoding

### ISSUE THREAD

**Issue by uwmyuan** [rodazuero/gmapsdistance#2]
I got these exceptions:

```
Error: 1: Input is not proper UTF-8, indicate encoding !
Bytes: 0xBA 0xC5 0x2D 0x32
```

when I ran the enquiry code

```
gmapsdistance(origin = "29.396905+105.579997", destination =  "29.650702+106.575104", mode = "driving", shape="long")
```

**Comment by rodazuero** [comment]
Thanks for reporting this bug. The function was using an xmlParse that did not recognize characters in non-standard latin-roman alphabet. We are using now a new parser. The updated version is on github. You can install directly from github by running:  

```
install.packages("devtools")
devtools::install_github("rodazuero/gmapsdistance")
```

Please, let us know if this solved the issue. If it does, we will upgrade ASAP to CRAN. 

Once again, thanks for reporting this issue.

**Comment by uwmyuan** [comment]
Thanks for your fast debug! I clone the project with devtools.  Now I have

```
Error in UseMethod("xmlChildren") : 
  no applicable method for 'xmlChildren' applied to an object of class "NULL"
```

when execute

`gmapsdistance(origin = "30.16101+105.8285", destination = "29.6507+106.5751", mode = "driving", shape = "long")`

**Comment by uwmyuan** [comment]
```
Error in UseMethod("xmlChildren") : 
  no applicable method for 'xmlChildren' applied to an object of class "NULL"
```

This error appears not stably. If it appears, it will stay in an uncertain time period. Then it is gone with the parameter set(origin, destination...) sometime. But for other test input(other origin-destinations), it appears again. This is so weird.

**Comment by njanetos** [comment]
Do you have a subscription to google's map service? If not, you are limited to 2,500 queries per day. If I run

```
for (i in 1:2501) {
   gmapsdistance(origin = "30.16101+105.8285", destination = "29.6507+106.5751", mode = "driving", shape = "long")
}
```

I get the error you describe on the 2501th query.

**Comment by uwmyuan** [comment]
@njanetos,

You are right! The error is caused by the daily query limit. I did not realize it because the error is thrown on 2133rd, 1319th queries. But after I use the key with set.api.key(), the following error appears.
`Error: XML content does not seem to be XML: 'https://maps.googleapis.com/maps/api/distancematrix/xml?origins=29.854605+105.789821&destinations=29.650702+106.575104&mode=driving&sensor=false&units=metric&departure_time=now&traffic_model=best_guess&key=$MYKEY'`

If pasting the url in browser, the xml content returns: 

```
<DistanceMatrixResponse>
<status>OK</status>
<origin_address>Xia Cheng Lu, Tongliang Qu, Chongqing Shi, China</origin_address>
<destination_address>Yubei, Chongqing, China</destination_address>
<row>
<element>
<status>OK</status>
<duration>
<value>4683</value>
<text>1 hour 18 mins</text>
</duration>
<distance>
<value>89122</value>
<text>89.1 km</text>
</distance>
<duration_in_traffic>
<value>4683</value>
<text>1 hour 18 mins</text>
</duration_in_traffic>
</element>
</row>
</DistanceMatrixResponse>
```

**Comment by uwmyuan** [comment]
`Error: XML content does not seem to be XML:`
The error is caused by xmlParse() cannot take https urls.
Please refer to  [http://stackoverflow.com/questions/23584514/error-xml-content-does-not-seem-to-be-xml-r-3-1-0](url)
#4

**Comment by rodazuero** [comment]
Thank you guys for your help.  
@njanetos : I merged your check for query limits. #3 Thank you so much, very helpful.  

@uwmyuan : Your pull request was done to a branch that did not include Nick's query limits. What I decided to do is to include your changes myself by hand given that it was easier this way. Please, let me know if the issue is resolved. It is odd that you get this error, we were not able to replicate. However, both work fine in various machines so I will take it as you have it if it resolves your issue. Thank you so much for your help.

**Comment by uwmyuan** [comment]
@rodazuero @njanetos 
This problem is solved. 
Thank you all for this project. It's really helpful.

**Comment by MichalPleva** [comment]
Hi guys,

I think this issue was not solved by `install.packages("devtools")` because when I run:
`gmapsdistance(origin = "50.070708+14.468469", destination = "50.075829+14.418829", mode = "walking")` 
it does not work, and unfortunately still shows the same error 
`Error: 1: Input is not proper UTF-8, indicate encoding !`. Could you please help me ? Thank you in advance.
