### ISSUE TITLE
Could not connect to server issue

### ISSUE THREAD

**Issue by sharonteo** [rodazuero/gmapsdistance#28]
Hello Rodrigo,
First of all thank you for sharing your gmapsdistance function! I am trying to run it but keep getting this error. Will you be able to help? Thank you!

> devtools::install_github("rodazuero/gmapsdistance")
Installation failed: Couldn't connect to server

Sharon

**Comment by rodazuero** [comment]
Thanks for your message. I think this error is related to the devtools or the configuration of your proxy rather than the gmapsdistance package. Check these threads:

https://stackoverflow.com/questions/16740256/error-installing-packages-from-github
https://github.com/hadley/devtools/issues/877
https://github.com/lucasmation/microdadosBrasil/issues/138

Hope this helps!
Rodrigo
